---
title: "Simulation"
author: "Ruilian Zhang"
date: "11/11/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```


## Let's simulate something

I have a function.
 
```{r}
sim_mean_sd = function(sample_size, mu = 3, sigma = 4) {
  
    sim_data = 
    tibble(
      x = rnorm(n = sample_size, mean = mu, sd = sigma)
    )
  
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
  
}
```

I can "simulate" by running this line.

```{r}
sim_mean_sd(30)
```


## Lets' simulate a lot

Let's start with a for loop.

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(sample_size = 30)
}

bind_rows(output)
```

Let's use a loop function.

```{r}
sim_results = 
  rerun(100, sim_mean_sd(sample_size = 30)) %>% 
  bind_rows()
```

Let's look at results.

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) + geom_density()

4/sqrt(30) # sample sd

sim_results %>% 
  summarize(
    average_sample_mean = mean(mean),
    sd_sample_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) + geom_density()
```


## Let's try other sampe sizes

```{r}
n_list = 
  list(
    "n = 30" = 30,
    "n = 60" = 60,
    "n = 120" = 120,
    "n = 240" = 240
  )

output = vector("list", length = 4)

output[[1]] = rerun(100, sim_mean_sd(sample_size = n_list[[1]])) %>% bind_rows()
output[[2]] = rerun(100, sim_mean_sd(sample_size = n_list[[2]])) %>% bind_rows()

for (i in 1:4) {
  
  output[[i]] = 
    rerun(100, sim_mean_sd(sample_size = n_list[[i]])) %>%
    bind_rows()
  
}
```


```{r}
# cache = T
# run once and save the result untill change this code chunk
# downside: easy to break
sim_results = 
  tibble(
    sample_size = c(30, 60, 120, 240)
  ) %>% 
    mutate(
      output_lists = map(.x = sample_size, ~ rerun(1000, sim_mean_sd(.x))),
      estimate_df = map(output_lists, bind_rows)
    ) %>% 
    select(-output_lists) %>% 
    unnest(estimate_df)
```

Do some dataframe things.

```{r}
sim_results %>%
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)
  ) %>% 
  ggplot(aes(x = sample_size, y = mean)) +
  geom_violin()
```

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarize(
    avg_samp_mean = mean(mean),
    sd_samp_mean = sd(mean)
  )

4 / sqrt(30)
4 / sqrt(60)
4 / sqrt(120)
4 / sqrt(240)
```

